<?php echo $this->doctype(); ?>

<html lang="en" ng-app="NGApplication">
    <head>
        <meta charset="utf-8">
        <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
        <?php echo $this->headTitle('Caramel '. $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile($this->basePath('js/angular.min.js'))
            ->appendFile($this->basePath('js/module/application/applicationController.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body ng-app="caramel"">
        <div class="container-fluid">
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#crm-ls-navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?= $this->url("home");?>">Caramel</a>
                    </div>

                    <div class="collapse navbar-collapse" id="crm-ls-navbar-collapse">

                        <!-- <ul class="nav navbar-nav">
                             <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                             <li><a href="#">Link</a></li>
                             <li class="dropdown">
                                 <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                                 <ul class="dropdown-menu" role="menu">
                                     <li><a href="#">Action</a></li>
                                     <li><a href="#">Another action</a></li>
                                     <li><a href="#">Something else here</a></li>
                                     <li class="divider"></li>
                                     <li><a href="#">Separated link</a></li>
                                     <li class="divider"></li>
                                     <li><a href="#">One more separated link</a></li>
                                 </ul>
                             </li>
                         </ul>-->

                        <form class="navbar-form navbar-left" role="search">
                            <div class="form-group">
                                <input type="text" class="form-control" id="nav-bar-search-bar-service-name" placeholder="What service are you looing for?">
                            </div>
                            <button type="submit" class="btn btn-link">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
                            </button>
                        </form>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a type="button" class="btn btn-link register-btn" href="<?= $this->url('zfcuser/register');?>">Register</a></li>
                            <li><a type="button" class="btn btn-link login-btn" href="<?= $this->url('zfcuser/login');?>">Login</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container vc-body">
                <?php echo $this->content; ?>
            </div> <!-- /container -->
        </div>
        <footer>
            <div class="container">
                <?php date_default_timezone_set('Europe/Paris');?>
                &copy; <?php echo date('Y') ?> Caramel
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
